### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by carlostighe**
Some small changes. 
Abstract Tablerow into a component to cut down on some repetition in the FeaturesDialog page and merge the `activeResultsTab` functions into one function.

### CODE REVIEW

**Comment by carlostighe** [comment]
Im using the prettier code formatter with vs code
https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

**Comment by carlostighe** [comment]
Sorry this is throwing an error. Going to close.

**Comment by andrewcottam** [comment]
I was just going to merge :) If you can put in the formatting as a pull request that would be great.

**Comment by carlostighe** [comment]
I fixed the issue. I'll add formatting tomorrow fix the issue and reopen request

**Comment by andrewcottam** [comment]
OK - cool!

**Pull request closed without merging**
